{% set provider = "google" %}
{% set version = "1.12.0" %}

{% set name = "terraform-provider-" + provider %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

{% set sha256 = "ad3622fc19e85380294cb837c36a963a3221c163fcb3497b487808146d57f020" %}
{% set sha256_win64 = "2f275fa63ccd679452340fb1c2513baf461dd3321e832a0c7b40af3a26c7389d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: {{ sha256_win64 }}  # [win64]

build:
  number: 0
  script:
    - XCOPY {{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - go 1.9.*  # [not win]
    - make  # [not win]
    - toolchain  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform Google provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
