{% set provider = "google" %}
{% set version = "1.17.1" %}

{% set name = "terraform-provider-" + provider %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/terraform-providers/{{ name|lower }}
    url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: a4bda284328fd5f52348a65b1abacf50ee2dc59ac6653ed9c6a826c5d7108fce  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    sha256: 11e6ea6dc2f2ea00171f9641b0cb5b8f446c9eff74461fb7db3e320cfb44634a  # [win64]

build:
  number: 1000
  script:
    - XCOPY src\github.com\terraform-providers\{{ name|lower }}\{{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform Google provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
